# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: hrsdev

# Labels to add to all resources and selectors.
commonLabels:  
  owner: Sanish
  app: healthrecordstack
  
# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
- deployment.yml
- service.yml

# Each entry in this list results in the creation of
# one Secret resource (it's a generator of n secrets).
secretGenerator:
- name: medicalchest-secret-configs
  namespace: hrsdev
  files:
    - config/.env
  type: "kubernetes.io/generic"

